config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies
  root to: redirect('/movies')

  get  'auth/:provider/callback' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  get  'auth/failure' => 'sessions#failure'
  get  'auth/twitter', :as => 'login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
    before_save :capitalize_title
    def capitalize_title
      self.title = self.title.split(/\s+/).map(&:downcase).
        map(&:capitalize).join(' ')
    end
  
    def self.all_ratings ; %w[G PG PG-13 R NC-17] ; end #  shortcut: array of strings
    validates :title, :presence => true
    validates :release_date, :presence => true
    validate :released_1930_or_later # uses custom validator below
    validates :rating, :inclusion => {:in => Movie.all_ratings},
              :unless => :grandfathered?
    def released_1930_or_later
      errors.add(:release_date, 'must be 1930 or later') if
          release_date && release_date < Date.parse('1 Jan 1930')
    end
    @@grandfathered_date = Date.parse('1 Nov 1968')
    def grandfathered?
      release_date && release_date < @@grandfathered_date
    end
end

app/models/moviegoer.rb
class Moviegoer < ActiveRecord::Base
    def self.create_with_omniauth(auth)
      Moviegoer.create!(
        :provider => auth["provider"],
        :uid => auth["uid"],
        :name => auth["info"]["name"])
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    protected # prevents method from being invoked by a route
    def set_current_user
      # we exploit the fact that the below query may return nil
      @current_user ||= Moviegoer.find_by(:id => session[:user_id])
    #   redirect_to login_path and return unless @current_userr
    end
  end

app/controllers/movies_controller.rb
# This file is app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def index
      @movies = Movie.all.sort{ |a, b| a.title<=>b.title}
    end

    def show
      id = params[:id] # retrieve movie ID from URI route
      @movie = Movie.find(id) # look up movie by unique ID
      render(:partial => 'movie', :object => @movie) if request.xhr?
      # will render app/views/movies/show.html.haml by default
    end

    def new
      @movie = Movie.new
      # default: render 'new' template
    end

    def create
      @movie = Movie.create!(movie_params)
      flash[:notice] = "#{@movie.title} was successfully created."
      redirect_to movies_path
    end

    def edit
      @movie = Movie.find params[:id]
    end

    def update
      @movie = Movie.find params[:id]
      @movie.update_attributes!(movie_params)
      flash[:notice] = "#{@movie.title} was successfully updated."
      respond_to do |client_wants|
        client_wants.html {  redirect_to movie_path(@movie)  } # as before
        client_wants.xml  {  render :xml => @movie.to_xml    }
      end
    end

    def destroy
      @movie = Movie.find(params[:id])
      @movie.destroy
      flash[:notice] = "Movie '#{@movie.title}' deleted."
      redirect_to movies_path
    end

    def search_tmdb
      # hardwire to simulate failure
      flash[:warning] = "'#{params[:search_terms]}' was not found in TMDb."
      redirect_to movies_path
    end

    private

    def movie_params
      params.require(:movie).permit(:title,:rating,:release_date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # user shouldn't have to be logged in before logging in!
    skip_before_action :set_current_user
    def create
      auth=request.env["omniauth.auth"]
      user=Moviegoer.find_by(:provider => auth["provider"], :uid => auth["uid"]) ||
        Moviegoer.create_with_omniauth(auth)
      session[:user_id] = user.id
      redirect_to movies_path
    end
    def destroy
      session.delete(:user_id)
      flash[:notice] = 'Logged out successfully.'
      redirect_to movies_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RottenPotatoes!
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'
    = csrf_meta_tags
  %body
    %h1.title= link_to 'Rotten Potatoes!', movies_path
    .container-fluid
      - if @current_user
        %p.welcome  Welcome, #{@current_user.name}!
        = link_to 'Log Out', logout_path, :method => :post
      - else
        %p.login= link_to 'Log in with your Twitter account', '/auth/twitter'
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
        
      = yield

app/views/movies/_movie.html.haml
%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit info', edit_movie_path(@movie)
= link_to 'Delete', movie_path(@movie), :method => :delete
= link_to 'Close', '', {:id => 'closeLink'}

app/views/movies/_movie_form.html.haml
-# in _movie_form.html.haml (the partial)
-# - unless @movie.errors.empty?
-#   #warning
-#     Errors prevented this movie from being #{controller.action_name}d:
-#     %ul
-#       - @movie.errors.full_messages.each do |error|
-#         %li= error

= label :movie, :title, 'Title'
= text_field :movie, 'title'

= label :movie, :rating, 'Rating'
= select :movie, :rating, Movie.all_ratings

= label :movie, :release_date, 'Released On'
= date_select :movie, :release_date, { start_year: 1930, end_year: Date.today.year }

app/views/movies/edit.html.haml
-# edit.html.haml using partial
%h2 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do
  = render :partial => 'movie_form'
  = submit_tag 'Update Movie Info'
  = link_to 'Cancel', movie_path(@movie)

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

%table#movies
  %thead
    %tr
      %th Index
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each_with_index do |movie, i|
      -# %tr{:class => ('adult' unless movie.rating =~ /^G|PG$/)}
      %tr{:class => movie.rating}
        %td= i+1
        %td= movie.title
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

-# %h1 Search TMDb for a movie

-# = form_tag :action => 'search_tmdb' do

-#   %label{:for => 'search_terms'} Search Terms
-#   = text_field_tag 'search_terms'
-#   = submit_tag 'Search TMDb'

app/views/movies/new.html.haml
-# new.html.haml using partial
%h2 Create New Movie

= form_tag '/movies', :method => :post do
  = render :partial => 'movie_form'
  = submit_tag 'Save Changes'
  = link_to 'Cancel', movies_path

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml
%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit info', edit_movie_path(@movie)
= link_to 'Delete', movie_path(@movie), :method => :delete
= link_to 'Back to movie list', movies_path